#!/bin/bash

# Copyright (c) 2023 Robert LaRocca http://www.laroccx.com

sudo cp -b -S .bak -v $PWD/clean.sh /usr/local/bin/clean
sudo chown root:root /usr/local/bin/clean
sudo chmod 0755 /usr/local/bin/clean

# vi: syntax=sh ts=2 noexpandtab
